version: '2.1'

services:
  fibo:
    image: smithx10/fibo:${TAG:-latest}
    command: >
      /usr/local/bin/containerpilot
    restart: always
    mem_limit: 512m
    network_mode: bridge
    environment:
      - CONSUL_AGENT=1
      - CONSUL=fibo-consul.svc.${TRITON_CNS_SEARCH_DOMAIN_PRIVATE}
      - FIBO_LOGPATH=/var/log
        
  fabio:
    image: smithx10/fabio:latest
    mem_limit: 2g
    restart: always
    labels:
      - triton.cns.services=fibo
    ports:
      - 80
      - 9998
    network_mode: bridge
    environment:
      - CONSUL_AGENT=1
      - CONSUL=fibo-consul.svc.${TRITON_CNS_SEARCH_DOMAIN_PRIVATE}
    command: >
      /usr/local/bin/containerpilot

  consul:
    image: autopilotpattern/consul:${TAG:-latest}
    command: >
       /usr/local/bin/containerpilot
    restart: always
    labels:
      - triton.cns.services=fibo-consul
    mem_limit: 128m
    ports:
      - 8500
    network_mode: bridge
    environment:
      - CONSUL=fibo-consul.svc.${TRITON_CNS_SEARCH_DOMAIN_PRIVATE}
